version: '2.1'

services:

  worker-paginator:
    image: elasticsearchpaginator/workerpaginator:${TAG:-latest}
    build:
      context: ./worker-paginator
      dockerfile: Dockerfile

  worker-paginator-calc:
    image: elasticsearchpaginator/workerpaginatorcalc:${TAG:-latest}
    build:
      context: ./worker-paginator-calc
      dockerfile: Dockerfile
