management:
  server:
    port: 8081

server:
  port: 8080

spring:
  application:
    name: worker-paginator
  rabbitmq:
    username: user
    password: password
  elasticsearch:
    rest:
      uris: http://locahost:9200

app:
  elasticsearch:
    query-entries-index: query-entries
    query-entries-index-number-replicas: 2
    query-entries-index-number-shards: 5
  rabbitmq:
    exchange-name: paginator
    queries-key: queries
    delete-queries-key: delete-queries
    delete-pages-key: delete-pages
    compute-pages-key: compute-pages
  min-interval-between-pages-refresh: 60m
  query-entries-ttl: 3d
